name: bin
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libprotobuf=5.29.3=hc99497a_0
  - libsentencepiece=0.2.0=h647b5c1_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - sentencepiece=0.2.0=h06a4308_4
  - sentencepiece-python=0.2.0=py311hdb19cb5_4
  - sentencepiece-spm=0.2.0=hdb19cb5_4
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.45.2
      - bleach==6.2.0
      - brokenaxes==0.6.2
      - cbor==1.0.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.6.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - entrypoints==0.4
      - evaluate==0.4.3
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flagembedding==1.3.5
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - idna==3.10
      - ijson==3.4.0
      - inscriptis==2.6.0
      - ipykernel==6.29.5
      - ipython==8.32.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - ir-datasets==0.5.11
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - lxml==6.0.0
      - lz4==4.4.4
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.1
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.16.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==3.11.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycparser==2.22
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==5.0.0
      - sentry-sdk==2.22.0
      - setuptools==80.9.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - staicc==0.1.1
      - sympy==1.14.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - torchaudio==2.6.0+cu124
      - torchvision==0.22.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.53.1
      - trec-car-tools==2.6
      - triton==3.3.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - unlzw3==0.2.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.19.6
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yarl==1.20.1
      - zlib-state==0.1.9
      - zstandard==0.23.0
prefix: /home/s2320415/anaconda3/envs/bin
